/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Thu Jul 18 15:02:09 2019. */

#include "txn.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ByteArray_fields[2] = {
    PB_FIELD(  1, BYTES   , REQUIRED, CALLBACK, FIRST, ByteArray, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t ProtoTransactionCoreInfo_fields[10] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ProtoTransactionCoreInfo, version, version, 0),
    PB_FIELD(  2, UINT64  , OPTIONAL, STATIC  , OTHER, ProtoTransactionCoreInfo, nonce, version, 0),
    PB_FIELD(  3, BYTES   , OPTIONAL, CALLBACK, OTHER, ProtoTransactionCoreInfo, toaddr, nonce, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, ProtoTransactionCoreInfo, senderpubkey, toaddr, &ByteArray_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, ProtoTransactionCoreInfo, amount, senderpubkey, &ByteArray_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, ProtoTransactionCoreInfo, gasprice, amount, &ByteArray_fields),
    PB_FIELD(  7, UINT64  , OPTIONAL, STATIC  , OTHER, ProtoTransactionCoreInfo, gaslimit, gasprice, 0),
    PB_FIELD(  8, BYTES   , OPTIONAL, CALLBACK, OTHER, ProtoTransactionCoreInfo, code, gaslimit, 0),
    PB_FIELD(  9, BYTES   , OPTIONAL, CALLBACK, OTHER, ProtoTransactionCoreInfo, data, code, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ProtoTransactionCoreInfo, senderpubkey) < 65536 && pb_membersize(ProtoTransactionCoreInfo, amount) < 65536 && pb_membersize(ProtoTransactionCoreInfo, gasprice) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ByteArray_ProtoTransactionCoreInfo)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ProtoTransactionCoreInfo, senderpubkey) < 256 && pb_membersize(ProtoTransactionCoreInfo, amount) < 256 && pb_membersize(ProtoTransactionCoreInfo, gasprice) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ByteArray_ProtoTransactionCoreInfo)
#endif


/* @@protoc_insertion_point(eof) */
